### ISSUE TITLE
Need a better code

### ISSUE THREAD

**Issue by mitsuakki** [mitsuakki/information-theory-papers#2]
## Scripts upgrade

One day this repository will need to have better code.

## Examples
What I'm saying about this can be explained really quickly by some simple examples (rather than big screenshot of the code)...

---
* From line 300 to line 313
* src/corrector/convolutional.py

```python
# Two children.
left, n, p, x = self.left._display_aux()
right, m, q, y = self.right._display_aux()
s = '[%s' % str(self.get_val()["dist"]) + "," + str(self.get_val()["output"]) + "]"
u = len(s)
first_line = (x + 1) * ' ' + (n - x - 1) * '_' + s + y * '_' + (m - y) * ' '
second_line = x * ' ' + '/' + (n - x - 1 + u + y) * ' ' + '\\' + (m - y - 1) * ' '
if p < q:
    left += [n * ' '] * (q - p)
elif q < p:
    right += [m * ' '] * (p - q)
zipped_lines = zip(left, right)
lines = [first_line, second_line] + [a + u * ' ' + b for a, b in zipped_lines]
return lines, n + m + u, max(p, q) + 2, n + u // 2
```
---

And, that's not the only one example i can give. I just don't want to appear as a poop...
Keep in mind that this project was an uni assignement with a 2 weeks deadline, when we knew nothing, started from 0 on a BIG english article with some scary math (not that deep but math formula are often scary for apparently nothing when you try to understand them)

### Todo list

- [ ] Add documentation and delete all french words in huffman compression
- [ ] Rework on wordle entropy system (not push atm because, this one is clearly an horror)
- [ ] Maybe continue to expand this research but that not the topic of the issue
